import type { Readable } from 'node:stream';

/**
 * Attachment storage abstraction (SOLO-MVP-01 design §10.5) — frozen PKG-1 contract.
 *
 * Drivers (implemented in PKG-2):
 *   - `local`: filesystem rooted at ATTACHMENT_STORAGE_DIR (development and automated tests)
 *   - `s3`:    S3-compatible object storage (e.g. Cloudflare R2) — preserved for production
 *   - `postgres`: private chunk table in PostgreSQL — free-tier staging without object
 *                 storage (PMOCORE-DEPLOY-VERCEL)
 *
 * Keys are generated by the server only, in the form `<projectId>/<attachmentId>`,
 * and are never derived from user input (REQ-042).
 */
export const STORAGE_KEY_PATTERN = /^[0-9a-f-]{36}\/[0-9a-f-]{36}$/;

export type StorageDriverName = 'local' | 's3' | 'postgres';

export interface AttachmentStorage {
  readonly driver: StorageDriverName;
  put(key: string, data: Buffer, contentType: string): Promise<void>;
  openRead(key: string): Promise<Readable>;
  /** Idempotent: deleting a missing object succeeds. */
  delete(key: string): Promise<void>;
  /** Used only by the purge/reconcile maintenance command. */
  list?(prefix: string): AsyncIterable<string>;
}

export function buildStorageKey(projectId: string, attachmentId: string): string {
  const key = `${projectId}/${attachmentId}`;
  assertStorageKey(key);
  return key;
}

export function assertStorageKey(key: string): void {
  if (!STORAGE_KEY_PATTERN.test(key)) {
    throw new Error('Invalid attachment storage key');
  }
}
